javascript_compressor: yui
javascripts:
  base:
    - public/javascripts/vendor/json2.js
    - public/javascripts/vendor/css_browser_selector.js
    - public/javascripts/vendor/modernizr.js
    - public/javascripts/vendor/jquery/*.js
    - public/javascripts/vendor/shuriken/**/*.js
    - public/javascripts/tedxperth.js
    - public/javascripts/tedxperth/util.js
    - public/javascripts/tedxperth/timestamps.js
    - public/javascripts/tedxperth/twitter.js
  admin:
    - public/javascripts/vendor/jquery/*.js
    - public/javascripts/vendor/css_browser_selector.js
    - public/javascripts/vendor/shuriken/**/*.js
    - public/javascripts/tedxperth.js
    - public/javascripts/tedxperth/util.js
    - public/javascripts/tedxperth/admin.js
  authentication_with_rpx_now:
    - public/javascripts/tedxperth/authentication.js
    - public/javascripts/tedxperth/rpx_now.js
  ck_editor:
    - public/javascripts/tedxperth/ck_editor.js
    - public/ckeditor/ckeditor.js
    - public/ckeditor/adapters/jquery.js
  convertable_editor:
    - public/javascripts/tedxperth/admin/convertable_editor.js
  ted_video_editor:
    - public/javascripts/tedxperth/admin/ted_video_editor.js
  events_page:
    - public/javascripts/tedxperth/ted_video.js
  home_page:
    - public/javascripts/tedxperth/home_page.js
  disqus:
    - public/javascripts/tedxperth/disqus.js
  gmaps_js:
    - public/javascripts/vendor/bhm-google-maps/*.js
stylesheets:
  base:
    - public/stylesheets/tedxperth.css
  admin:
    - public/stylesheets/tedxperth-admin.css